import type { Metadata } from 'next'
import './globals.css'
import { noto_sans } from './ui/fonts'
import Header from './ui/components/Header/Header'
import Footer from './ui/components/Footer/Footer'
import Sidebar from './ui/components/SideBar/Sidebar'
import styles from '@/app/layout.module.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>
         <div className={styles.wrapper}>
          <Header className={styles.header}/>
          <Sidebar className={styles.sidebar}/>
          <div className={styles.body}>{children}</div>
          <Footer className={styles.footer}/>
        </div> 
      </body>
    </html>
  )
}
